CREATE TABLE IF NOT EXISTS research_station_reference (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  map_number INTEGER NOT NULL,
  station_name TEXT NOT NULL,
  country TEXT NOT NULL,
  source_title TEXT NOT NULL DEFAULT 'COMNAP Research Stations Map',
  source_period TEXT NOT NULL DEFAULT '1998-2005',
  source_url TEXT NOT NULL DEFAULT '/research-stations-map.pdf',
  UNIQUE(source_title, map_number)
);

CREATE INDEX IF NOT EXISTS idx_research_station_reference_country
  ON research_station_reference(country, station_name);

INSERT OR IGNORE INTO research_station_reference
  (map_number,station_name,country,source_title,source_period,source_url)
VALUES
  (1,'Vernadasky','Ukraine','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (2,'Palmer','United States','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (3,'Brown','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (4,'Escudero','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (5,'Decepción','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (6,'Cámara','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (7,'Risopatron','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (8,'Prat','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (9,'Juan Carlos I','Spain','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (10,'Ripamonti','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (11,'O''Higgins','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (12,'Great Wall','China','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (13,'Bellingshausen','Russia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (14,'Frei','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (15,'Artigas','Uruguay','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (16,'King Sejong','Republic of Korea','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (17,'Jubany','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (18,'Dallmann','Germany','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (19,'Arctowski','Poland','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (20,'Ferraz','Brazil','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (21,'Ochridiski','Bulgaria','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (22,'Macchu Picchu','Peru','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (23,'Esperanza','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (24,'GGV','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (25,'Marambio','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (26,'Primavera','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (27,'Signy','United Kingdom','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (28,'Petrel','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (29,'Orcadas','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (30,'Bird Is','United Kingdom','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (31,'Alfred-Faure','France','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (32,'Sobral','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (33,'Belgrano II','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (34,'Halley','United Kingdom','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (35,'Aboa','Finland','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (36,'SANAE IV','South Africa','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (37,'Neumayer','Germany','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (38,'E-Base','South Africa','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (39,'Troll','Norway','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (40,'Tor','Norway','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (41,'Maitri','India','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (42,'Gough Is','South Africa','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (43,'Marion Is','South Africa','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (44,'Novo','Russia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (45,'Wasa','Sweden','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (46,'Asuka','Japan','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (47,'Dome Fuji','Japan','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (48,'Miznho','Japan','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (49,'Syowa','Japan','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (50,'Molo','Russia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (51,'PAF','France','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (52,'Heard Is','Australia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (53,'Mawson','Australia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (54,'Soyuz','Russia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (55,'Druzhnaya 4','Russia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (56,'Progress','Russia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (57,'Zhongshan','China','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (58,'Law Base','Australia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (59,'Davis','Australia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (60,'South Pole','United States','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (61,'Mirny','Russia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (62,'Vostok','Russia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (63,'Concordia','France','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (64,'Concordia','Italy','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (65,'Casey','Australia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (66,'Law Dome','Australia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (67,'DDU','France','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (68,'Macquarie Is','Australia','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (69,'Mario Zucchelli','Italy','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (70,'McMurdo','United States','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (71,'Scott','New Zealand','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (72,'Martin-de-Viviès','France','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (73,'San Martin','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (74,'Rothera','United Kingdom','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (75,'Carvajal','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (76,'Matienzo','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (77,'Melchior','Argentina','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (78,'Yelcho','Chile','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (79,'Vicente','Ecuador','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (80,'Gabriel de Castilla','Spain','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (81,'Kohnen','Germany','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf'),
  (82,'King Edward Point','United Kingdom','COMNAP Research Stations Map','1998-2005','/research-stations-map.pdf');
